FROM registry.dev.chelizitech.com/public/centos:7

MAINTAINER chetailian

RUN cp -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
RUN yum install libunwind icu -y \
    && yum install dotnet-sdk-2.1 -y \
    && yum clean all \
    && dotnet --info

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8
