FROM centos

MAINTAINER remoting <remoting@qq.com>

ENV JAVA_HOME /java/jdk1.8
ENV CLASSPATH=.:$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH=$PATH:$JAVA_HOME/bin
